/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type BookingId = string;
export interface TimeSlot {
    id: string;
    startTime: bigint;
    endTime: bigint;
    isAvailable: boolean;
}
export type PhotoId = string;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface PhotoMetadata {
    id: PhotoId;
    categories: Array<string>;
    title: string;
    description: string;
    uploadDate: bigint;
    fileReference: ExternalBlob;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface PaymentNotification {
    paymentStatus: string;
    paymentMethod: string;
    bookingId: string;
    paymentId: string;
    amount: bigint;
}
export interface Payment {
    id: PaymentId;
    status: string;
    paymentMethod: string;
    bookingId: BookingId;
    currency: string;
    timestamp: bigint;
    amount: bigint;
}
export type PaymentId = string;
export interface SavePhotoArgs {
    id: string;
    categories: Array<string>;
    title: string;
    description: string;
    uploadDate: bigint;
    fileReference: ExternalBlob;
}
export interface CreateBookingArgs {
    serviceType: string;
    clientName: string;
    scheduledDate: bigint;
    email: string;
    phone: string;
}
export interface Booking {
    id: BookingId;
    status: string;
    serviceType: string;
    clientName: string;
    scheduledDate: bigint;
    email: string;
    phone: string;
}
export interface UserProfile {
    name: string;
    email: string;
    phone: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    checkAvailability(requestedStartTime: bigint, requestedEndTime: bigint): Promise<boolean>;
    createBooking(args: CreateBookingArgs): Promise<BookingId>;
    deleteBooking(id: BookingId): Promise<void>;
    deletePhoto(id: PhotoId): Promise<void>;
    findBookingsByDateRange(startDate: bigint, endDate: bigint): Promise<Array<Booking>>;
    findBookingsByName(name: string): Promise<Array<Booking>>;
    findPaymentsByBookingId(bookingId: string): Promise<Array<Payment>>;
    findPaymentsByDateRange(startDate: bigint, endDate: bigint): Promise<Array<Payment>>;
    getAllBookings(): Promise<Array<Booking>>;
    getBookingsByEmail(email: string): Promise<Array<Booking>>;
    getBookingsByStatus(status: string): Promise<Array<Booking>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getPayments(): Promise<Array<Payment>>;
    getPaymentsByStatus(status: string): Promise<Array<Payment>>;
    getPhotos(): Promise<Array<PhotoMetadata>>;
    getPhotosByCategory(category: string): Promise<Array<PhotoMetadata>>;
    getPhotosByCategoryAndDate(category: string, startDate: bigint, endDate: bigint): Promise<Array<PhotoMetadata>>;
    getTimeSlots(): Promise<Array<TimeSlot>>;
    getUpcomingBookings(): Promise<Array<Booking>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    handlePaymentUpdate(notification: PaymentNotification): Promise<void>;
    initializeAccessControl(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    processRazorpayPayment(payment: Payment): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    savePhoto(photo: SavePhotoArgs): Promise<void>;
    savePhotoBatch(photosArray: Array<SavePhotoArgs>): Promise<void>;
    setTimeSlotAvailability(id: string, isAvailable: boolean): Promise<void>;
    setTimeSlots(slots: Array<TimeSlot>): Promise<void>;
    updateBooking(id: string, clientName: string, email: string, phone: string, serviceType: string, scheduledDate: bigint, status: string): Promise<void>;
    updateBookingStatus(bookingId: string, newStatus: string): Promise<void>;
    updatePayment(id: string, status: string): Promise<void>;
    updatePhoto(id: string, title: string, description: string, categories: Array<string>, uploadDate: bigint, fileReference: ExternalBlob): Promise<void>;
}
import type { ExternalBlob as _ExternalBlob, PhotoId as _PhotoId, PhotoMetadata as _PhotoMetadata, SavePhotoArgs as _SavePhotoArgs, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this.uploadFile, this.downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this.uploadFile, this.downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this.uploadFile, this.downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
    async checkAvailability(arg0: bigint, arg1: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.checkAvailability(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkAvailability(arg0, arg1);
            return result;
        }
    }
    async createBooking(arg0: CreateBookingArgs): Promise<BookingId> {
        if (this.processError) {
            try {
                const result = await this.actor.createBooking(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBooking(arg0);
            return result;
        }
    }
    async deleteBooking(arg0: BookingId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBooking(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBooking(arg0);
            return result;
        }
    }
    async deletePhoto(arg0: PhotoId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePhoto(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePhoto(arg0);
            return result;
        }
    }
    async findBookingsByDateRange(arg0: bigint, arg1: bigint): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.findBookingsByDateRange(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.findBookingsByDateRange(arg0, arg1);
            return result;
        }
    }
    async findBookingsByName(arg0: string): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.findBookingsByName(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.findBookingsByName(arg0);
            return result;
        }
    }
    async findPaymentsByBookingId(arg0: string): Promise<Array<Payment>> {
        if (this.processError) {
            try {
                const result = await this.actor.findPaymentsByBookingId(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.findPaymentsByBookingId(arg0);
            return result;
        }
    }
    async findPaymentsByDateRange(arg0: bigint, arg1: bigint): Promise<Array<Payment>> {
        if (this.processError) {
            try {
                const result = await this.actor.findPaymentsByDateRange(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.findPaymentsByDateRange(arg0, arg1);
            return result;
        }
    }
    async getAllBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBookings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBookings();
            return result;
        }
    }
    async getBookingsByEmail(arg0: string): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingsByEmail(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingsByEmail(arg0);
            return result;
        }
    }
    async getBookingsByStatus(arg0: string): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingsByStatus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingsByStatus(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n10(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n10(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n11(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n11(this.uploadFile, this.downloadFile, result);
        }
    }
    async getPayments(): Promise<Array<Payment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPayments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPayments();
            return result;
        }
    }
    async getPaymentsByStatus(arg0: string): Promise<Array<Payment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPaymentsByStatus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPaymentsByStatus(arg0);
            return result;
        }
    }
    async getPhotos(): Promise<Array<PhotoMetadata>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPhotos();
                return from_candid_vec_n13(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPhotos();
            return from_candid_vec_n13(this.uploadFile, this.downloadFile, result);
        }
    }
    async getPhotosByCategory(arg0: string): Promise<Array<PhotoMetadata>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPhotosByCategory(arg0);
                return from_candid_vec_n13(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPhotosByCategory(arg0);
            return from_candid_vec_n13(this.uploadFile, this.downloadFile, result);
        }
    }
    async getPhotosByCategoryAndDate(arg0: string, arg1: bigint, arg2: bigint): Promise<Array<PhotoMetadata>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPhotosByCategoryAndDate(arg0, arg1, arg2);
                return from_candid_vec_n13(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPhotosByCategoryAndDate(arg0, arg1, arg2);
            return from_candid_vec_n13(this.uploadFile, this.downloadFile, result);
        }
    }
    async getTimeSlots(): Promise<Array<TimeSlot>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTimeSlots();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTimeSlots();
            return result;
        }
    }
    async getUpcomingBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUpcomingBookings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUpcomingBookings();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n10(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n10(this.uploadFile, this.downloadFile, result);
        }
    }
    async handlePaymentUpdate(arg0: PaymentNotification): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.handlePaymentUpdate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.handlePaymentUpdate(arg0);
            return result;
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async processRazorpayPayment(arg0: Payment): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.processRazorpayPayment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.processRazorpayPayment(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async savePhoto(arg0: SavePhotoArgs): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.savePhoto(await to_candid_SavePhotoArgs_n17(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.savePhoto(await to_candid_SavePhotoArgs_n17(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async savePhotoBatch(arg0: Array<SavePhotoArgs>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.savePhotoBatch(await to_candid_vec_n20(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.savePhotoBatch(await to_candid_vec_n20(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async setTimeSlotAvailability(arg0: string, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setTimeSlotAvailability(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setTimeSlotAvailability(arg0, arg1);
            return result;
        }
    }
    async setTimeSlots(arg0: Array<TimeSlot>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setTimeSlots(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setTimeSlots(arg0);
            return result;
        }
    }
    async updateBooking(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: bigint, arg6: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBooking(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBooking(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async updateBookingStatus(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBookingStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBookingStatus(arg0, arg1);
            return result;
        }
    }
    async updatePayment(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePayment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePayment(arg0, arg1);
            return result;
        }
    }
    async updatePhoto(arg0: string, arg1: string, arg2: string, arg3: Array<string>, arg4: bigint, arg5: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePhoto(arg0, arg1, arg2, arg3, arg4, await to_candid_ExternalBlob_n19(this.uploadFile, this.downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePhoto(arg0, arg1, arg2, arg3, arg4, await to_candid_ExternalBlob_n19(this.uploadFile, this.downloadFile, arg5));
            return result;
        }
    }
}
async function from_candid_ExternalBlob_n16(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await downloadFile(value);
}
async function from_candid_PhotoMetadata_n14(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PhotoMetadata): Promise<PhotoMetadata> {
    return await from_candid_record_n15(uploadFile, downloadFile, value);
}
function from_candid_UserRole_n11(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n12(uploadFile, downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(uploadFile, downloadFile, value);
}
function from_candid_opt_n10(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n15(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _PhotoId;
    categories: Array<string>;
    title: string;
    description: string;
    uploadDate: bigint;
    fileReference: _ExternalBlob;
}): Promise<{
    id: PhotoId;
    categories: Array<string>;
    title: string;
    description: string;
    uploadDate: bigint;
    fileReference: ExternalBlob;
}> {
    return {
        id: value.id,
        categories: value.categories,
        title: value.title,
        description: value.description,
        uploadDate: value.uploadDate,
        fileReference: await from_candid_ExternalBlob_n16(uploadFile, downloadFile, value.fileReference)
    };
}
function from_candid_record_n5(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(uploadFile, downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(uploadFile, downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n12(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n13(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PhotoMetadata>): Promise<Array<PhotoMetadata>> {
    return await Promise.all(value.map(async (x)=>await from_candid_PhotoMetadata_n14(uploadFile, downloadFile, x)));
}
async function to_candid_ExternalBlob_n19(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await uploadFile(value);
}
async function to_candid_SavePhotoArgs_n17(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SavePhotoArgs): Promise<_SavePhotoArgs> {
    return await to_candid_record_n18(uploadFile, downloadFile, value);
}
function to_candid_UserRole_n8(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(uploadFile, downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(uploadFile, downloadFile, value);
}
function to_candid_opt_n1(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(uploadFile, downloadFile, value));
}
async function to_candid_record_n18(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    categories: Array<string>;
    title: string;
    description: string;
    uploadDate: bigint;
    fileReference: ExternalBlob;
}): Promise<{
    id: string;
    categories: Array<string>;
    title: string;
    description: string;
    uploadDate: bigint;
    fileReference: _ExternalBlob;
}> {
    return {
        id: value.id,
        categories: value.categories,
        title: value.title,
        description: value.description,
        uploadDate: value.uploadDate,
        fileReference: await to_candid_ExternalBlob_n19(uploadFile, downloadFile, value.fileReference)
    };
}
function to_candid_record_n3(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n9(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
async function to_candid_vec_n20(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<SavePhotoArgs>): Promise<Array<_SavePhotoArgs>> {
    return await Promise.all(value.map(async (x)=>await to_candid_SavePhotoArgs_n17(uploadFile, downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, uploadFile, downloadFile, options.processError);
}
