/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CreateBookingArgs = IDL.Record({
  'serviceType' : IDL.Text,
  'clientName' : IDL.Text,
  'scheduledDate' : IDL.Int,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const BookingId = IDL.Text;
export const PhotoId = IDL.Text;
export const Booking = IDL.Record({
  'id' : BookingId,
  'status' : IDL.Text,
  'serviceType' : IDL.Text,
  'clientName' : IDL.Text,
  'scheduledDate' : IDL.Int,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const PaymentId = IDL.Text;
export const Payment = IDL.Record({
  'id' : PaymentId,
  'status' : IDL.Text,
  'paymentMethod' : IDL.Text,
  'bookingId' : BookingId,
  'currency' : IDL.Text,
  'timestamp' : IDL.Int,
  'amount' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const PhotoMetadata = IDL.Record({
  'id' : PhotoId,
  'categories' : IDL.Vec(IDL.Text),
  'title' : IDL.Text,
  'description' : IDL.Text,
  'uploadDate' : IDL.Int,
  'fileReference' : ExternalBlob,
});
export const TimeSlot = IDL.Record({
  'id' : IDL.Text,
  'startTime' : IDL.Int,
  'endTime' : IDL.Int,
  'isAvailable' : IDL.Bool,
});
export const PaymentNotification = IDL.Record({
  'paymentStatus' : IDL.Text,
  'paymentMethod' : IDL.Text,
  'bookingId' : IDL.Text,
  'paymentId' : IDL.Text,
  'amount' : IDL.Nat,
});
export const SavePhotoArgs = IDL.Record({
  'id' : IDL.Text,
  'categories' : IDL.Vec(IDL.Text),
  'title' : IDL.Text,
  'description' : IDL.Text,
  'uploadDate' : IDL.Int,
  'fileReference' : ExternalBlob,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkAvailability' : IDL.Func([IDL.Int, IDL.Int], [IDL.Bool], ['query']),
  'createBooking' : IDL.Func([CreateBookingArgs], [BookingId], []),
  'deleteBooking' : IDL.Func([BookingId], [], []),
  'deletePhoto' : IDL.Func([PhotoId], [], []),
  'findBookingsByDateRange' : IDL.Func(
      [IDL.Int, IDL.Int],
      [IDL.Vec(Booking)],
      ['query'],
    ),
  'findBookingsByName' : IDL.Func([IDL.Text], [IDL.Vec(Booking)], ['query']),
  'findPaymentsByBookingId' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Payment)],
      ['query'],
    ),
  'findPaymentsByDateRange' : IDL.Func(
      [IDL.Int, IDL.Int],
      [IDL.Vec(Payment)],
      ['query'],
    ),
  'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getBookingsByEmail' : IDL.Func([IDL.Text], [IDL.Vec(Booking)], ['query']),
  'getBookingsByStatus' : IDL.Func([IDL.Text], [IDL.Vec(Booking)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
  'getPaymentsByStatus' : IDL.Func([IDL.Text], [IDL.Vec(Payment)], ['query']),
  'getPhotos' : IDL.Func([], [IDL.Vec(PhotoMetadata)], ['query']),
  'getPhotosByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(PhotoMetadata)],
      ['query'],
    ),
  'getPhotosByCategoryAndDate' : IDL.Func(
      [IDL.Text, IDL.Int, IDL.Int],
      [IDL.Vec(PhotoMetadata)],
      ['query'],
    ),
  'getTimeSlots' : IDL.Func([], [IDL.Vec(TimeSlot)], ['query']),
  'getUpcomingBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'handlePaymentUpdate' : IDL.Func([PaymentNotification], [], []),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'processRazorpayPayment' : IDL.Func([Payment], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'savePhoto' : IDL.Func([SavePhotoArgs], [], []),
  'savePhotoBatch' : IDL.Func([IDL.Vec(SavePhotoArgs)], [], []),
  'setTimeSlotAvailability' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'setTimeSlots' : IDL.Func([IDL.Vec(TimeSlot)], [], []),
  'updateBooking' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Int, IDL.Text],
      [],
      [],
    ),
  'updateBookingStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updatePayment' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updatePhoto' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Int, ExternalBlob],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CreateBookingArgs = IDL.Record({
    'serviceType' : IDL.Text,
    'clientName' : IDL.Text,
    'scheduledDate' : IDL.Int,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const BookingId = IDL.Text;
  const PhotoId = IDL.Text;
  const Booking = IDL.Record({
    'id' : BookingId,
    'status' : IDL.Text,
    'serviceType' : IDL.Text,
    'clientName' : IDL.Text,
    'scheduledDate' : IDL.Int,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const PaymentId = IDL.Text;
  const Payment = IDL.Record({
    'id' : PaymentId,
    'status' : IDL.Text,
    'paymentMethod' : IDL.Text,
    'bookingId' : BookingId,
    'currency' : IDL.Text,
    'timestamp' : IDL.Int,
    'amount' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const PhotoMetadata = IDL.Record({
    'id' : PhotoId,
    'categories' : IDL.Vec(IDL.Text),
    'title' : IDL.Text,
    'description' : IDL.Text,
    'uploadDate' : IDL.Int,
    'fileReference' : ExternalBlob,
  });
  const TimeSlot = IDL.Record({
    'id' : IDL.Text,
    'startTime' : IDL.Int,
    'endTime' : IDL.Int,
    'isAvailable' : IDL.Bool,
  });
  const PaymentNotification = IDL.Record({
    'paymentStatus' : IDL.Text,
    'paymentMethod' : IDL.Text,
    'bookingId' : IDL.Text,
    'paymentId' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const SavePhotoArgs = IDL.Record({
    'id' : IDL.Text,
    'categories' : IDL.Vec(IDL.Text),
    'title' : IDL.Text,
    'description' : IDL.Text,
    'uploadDate' : IDL.Int,
    'fileReference' : ExternalBlob,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkAvailability' : IDL.Func([IDL.Int, IDL.Int], [IDL.Bool], ['query']),
    'createBooking' : IDL.Func([CreateBookingArgs], [BookingId], []),
    'deleteBooking' : IDL.Func([BookingId], [], []),
    'deletePhoto' : IDL.Func([PhotoId], [], []),
    'findBookingsByDateRange' : IDL.Func(
        [IDL.Int, IDL.Int],
        [IDL.Vec(Booking)],
        ['query'],
      ),
    'findBookingsByName' : IDL.Func([IDL.Text], [IDL.Vec(Booking)], ['query']),
    'findPaymentsByBookingId' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Payment)],
        ['query'],
      ),
    'findPaymentsByDateRange' : IDL.Func(
        [IDL.Int, IDL.Int],
        [IDL.Vec(Payment)],
        ['query'],
      ),
    'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getBookingsByEmail' : IDL.Func([IDL.Text], [IDL.Vec(Booking)], ['query']),
    'getBookingsByStatus' : IDL.Func([IDL.Text], [IDL.Vec(Booking)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
    'getPaymentsByStatus' : IDL.Func([IDL.Text], [IDL.Vec(Payment)], ['query']),
    'getPhotos' : IDL.Func([], [IDL.Vec(PhotoMetadata)], ['query']),
    'getPhotosByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(PhotoMetadata)],
        ['query'],
      ),
    'getPhotosByCategoryAndDate' : IDL.Func(
        [IDL.Text, IDL.Int, IDL.Int],
        [IDL.Vec(PhotoMetadata)],
        ['query'],
      ),
    'getTimeSlots' : IDL.Func([], [IDL.Vec(TimeSlot)], ['query']),
    'getUpcomingBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'handlePaymentUpdate' : IDL.Func([PaymentNotification], [], []),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'processRazorpayPayment' : IDL.Func([Payment], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'savePhoto' : IDL.Func([SavePhotoArgs], [], []),
    'savePhotoBatch' : IDL.Func([IDL.Vec(SavePhotoArgs)], [], []),
    'setTimeSlotAvailability' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'setTimeSlots' : IDL.Func([IDL.Vec(TimeSlot)], [], []),
    'updateBooking' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Int, IDL.Text],
        [],
        [],
      ),
    'updateBookingStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updatePayment' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updatePhoto' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Int,
          ExternalBlob,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };