/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'id' : BookingId,
  'status' : string,
  'serviceType' : string,
  'clientName' : string,
  'scheduledDate' : bigint,
  'email' : string,
  'phone' : string,
}
export type BookingId = string;
export interface CreateBookingArgs {
  'serviceType' : string,
  'clientName' : string,
  'scheduledDate' : bigint,
  'email' : string,
  'phone' : string,
}
export type ExternalBlob = Uint8Array;
export interface Payment {
  'id' : PaymentId,
  'status' : string,
  'paymentMethod' : string,
  'bookingId' : BookingId,
  'currency' : string,
  'timestamp' : bigint,
  'amount' : bigint,
}
export type PaymentId = string;
export interface PaymentNotification {
  'paymentStatus' : string,
  'paymentMethod' : string,
  'bookingId' : string,
  'paymentId' : string,
  'amount' : bigint,
}
export type PhotoId = string;
export interface PhotoMetadata {
  'id' : PhotoId,
  'categories' : Array<string>,
  'title' : string,
  'description' : string,
  'uploadDate' : bigint,
  'fileReference' : ExternalBlob,
}
export interface SavePhotoArgs {
  'id' : string,
  'categories' : Array<string>,
  'title' : string,
  'description' : string,
  'uploadDate' : bigint,
  'fileReference' : ExternalBlob,
}
export interface TimeSlot {
  'id' : string,
  'startTime' : bigint,
  'endTime' : bigint,
  'isAvailable' : boolean,
}
export interface UserProfile {
  'name' : string,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkAvailability' : ActorMethod<[bigint, bigint], boolean>,
  'createBooking' : ActorMethod<[CreateBookingArgs], BookingId>,
  'deleteBooking' : ActorMethod<[BookingId], undefined>,
  'deletePhoto' : ActorMethod<[PhotoId], undefined>,
  'findBookingsByDateRange' : ActorMethod<[bigint, bigint], Array<Booking>>,
  'findBookingsByName' : ActorMethod<[string], Array<Booking>>,
  'findPaymentsByBookingId' : ActorMethod<[string], Array<Payment>>,
  'findPaymentsByDateRange' : ActorMethod<[bigint, bigint], Array<Payment>>,
  'getAllBookings' : ActorMethod<[], Array<Booking>>,
  'getBookingsByEmail' : ActorMethod<[string], Array<Booking>>,
  'getBookingsByStatus' : ActorMethod<[string], Array<Booking>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPayments' : ActorMethod<[], Array<Payment>>,
  'getPaymentsByStatus' : ActorMethod<[string], Array<Payment>>,
  'getPhotos' : ActorMethod<[], Array<PhotoMetadata>>,
  'getPhotosByCategory' : ActorMethod<[string], Array<PhotoMetadata>>,
  'getPhotosByCategoryAndDate' : ActorMethod<
    [string, bigint, bigint],
    Array<PhotoMetadata>
  >,
  'getTimeSlots' : ActorMethod<[], Array<TimeSlot>>,
  'getUpcomingBookings' : ActorMethod<[], Array<Booking>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'handlePaymentUpdate' : ActorMethod<[PaymentNotification], undefined>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'processRazorpayPayment' : ActorMethod<[Payment], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'savePhoto' : ActorMethod<[SavePhotoArgs], undefined>,
  'savePhotoBatch' : ActorMethod<[Array<SavePhotoArgs>], undefined>,
  'setTimeSlotAvailability' : ActorMethod<[string, boolean], undefined>,
  'setTimeSlots' : ActorMethod<[Array<TimeSlot>], undefined>,
  'updateBooking' : ActorMethod<
    [string, string, string, string, string, bigint, string],
    undefined
  >,
  'updateBookingStatus' : ActorMethod<[string, string], undefined>,
  'updatePayment' : ActorMethod<[string, string], undefined>,
  'updatePhoto' : ActorMethod<
    [string, string, string, Array<string>, bigint, ExternalBlob],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];